name: notebook
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - jupyterlab >=3.0
  - jupyter-server-proxy
  - scikit-learn
  - pandas
  - beautifulsoup4
  - skyfield
  - matplotlib
  # - requests
  # - tornado
  - pip:
    - pyqrcode
    - usd-core
    - -e ../plotAR-py
