#!/bin/bash

pwd
echo $CONDA_PREFIX

## would need to do this as root
# mkdir -p $CONDA_PREFIX/etc/jupyter/jupyter_notebook_config.d/
# cp plotAR-py/plotar/etc/* $CONDA_PREFIX/etc/jupyter/jupyter_notebook_config.d/

mkdir -p .jupyter/jupyter_notebook_config.d
cp plotAR-py/plotar/etc/* .jupyter/jupyter_notebook_config.d/

# let's try to get /lab as default path:
echo "c.NotebookApp.default_url = '/lab'" >> .jupyter/jupyter_notebook_config.py
echo "c.ServerApp.default_url = '/lab'" >> .jupyter/jupyter_server_config.py



## Get's overwritten later anyway :-|
# configure RStudio
# mkdir -p /etc/rstudio
# echo "rsession-ld-library-path=$CONDA_PREFIX/lib" >> /etc/rstudio/rserver.conf

cp .binder/Rprofile ~/.Rprofile

R CMD INSTALL ./plotAR-R/

mkdir -p $CONDA_PREFIX/lib/R/etc/
echo "Sys.setenv(RETICULATE_PYTHON='$CONDA_PREFIX/bin/python')" >> $CONDA_PREFIX/lib/R/etc/Rprofile.site

##### Examples data pre-load
mkdir -p tmp
cd tmp

# for CH
curl -LO https://data.geo.admin.ch/ch.swisstopo.digitales-hoehenmodell_25/data.zip
unzip data.zip DHM200.asc

# for planets
## mybinder does not allow ftp downloads:
#curl -LO ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp

cd ..
